### ISSUE TITLE
Add lz git section - part iii second part after CSR service - CSR itself - apply instructions 

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pubsec-declarative-toolkit#195]
2nd csr yaml
https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/tree/main/solutions/landing-zone#git

create the repo yaml
```
apiVersion: sourcerepo.cnrm.cloud.google.com/v1beta1
kind: SourceRepoRepository
metadata:
  name: my-lz-repo
  namespace: config-control
```

missing the kubectl apply
see
https://cloud.google.com/anthos-config-management/docs/how-to/config-controller-setup#manage-resources

```
root_@cloudshell:~/wse_github/obriensystems/pubsec-declarative-toolkit/solutions/landing-zone (controller-agz-1201)$ vi repo.yaml
root_@cloudshell:~/wse_github/obriensystems/pubsec-declarative-toolkit/solutions/landing-zone (controller-agz-1201)$ kubectl apply -f repo.yaml
sourcereporepository.sourcerepo.cnrm.cloud.google.com/my-lz-repo created
root_@cloudshell:~/wse_github/obriensystems/pubsec-declarative-toolkit/solutions/landing-zone (controller-agz-1201)$ kubectl wait -f repo.yaml --for=condition=Ready
error: timed out waiting for the condition on sourcereporepositories/my-lz-repo
```
expand on
https://cloud.google.com/anthos-config-management/docs/how-to/config-controller-setup#set_up_gitops
