### ISSUE TITLE
Code Linting Discussion

### ISSUE THREAD

**Issue by KingBain** [GoogleCloudPlatform/pubsec-declarative-toolkit#274]
I've een working on some of the code in my own repo, getting some of the CICD pipelines configured.

In that fork, when I enabled Yaml linting via Super-Linter I noticed that a lot of lining warnings were returning. 

Manually going through the code, most of the linting issues are issues with code blocks that have been copy/pasted and also I think  one of the contributors is/was running Prettier code autop formatter. 

So I was wondering if we could have a deeper discussion about a yaml format for this code base. 

Something like 

```
rules:
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1
  document-end:
    present: true
  document-start:
    present: true
  line-length:
    max: 80
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: false
```
