### ISSUE TITLE
docs: project admin role does not exist - think we meant project iam admin - testing this as part of a clean deploy

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pubsec-declarative-toolkit#570]
Project Admin
to
Project IAM Admin

but check first in step 1 of https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/blob/main/docs/landing-zone-v2/README.md#1-complete-the-bootstrap-procedure

**Comment by obriensystems** [comment]
testing
```
oot_@cloudshell:~/pdt-ls/obriensystems/pubsec-declarative-toolkit/solutions (kcc-boot-ls)$ ./setup.sh -b kcc-boot-ls -u ls -c true -l false -r false -d false  
Date: Fri 20 Oct 2023 06:26:30 PM UTC
Timestamp: 1697826390
running with: -b kcc-boot-ls -u ls -c true -l false -r false -d false -p 
Updated property [core/project].
Switched back to boot project kcc-boot-ls
Start: 1697826391
unique string: ls
REGION: northamerica-northeast1
NETWORK: kcc-ls-vpc
SUBNET: kcc-ls-sn
CLUSTER: kcc-ls1
Reusing project: 
CC_PROJECT_ID: 
BOOT_PROJECT_ID: kcc-boot-ls
BILLING_ID: 01E6E8-A42E99-D21FF3
ORG_ID: 59485982875
applying roles to the super admin SUPER_ADMIN_EMAIL: root@landing.systems
ROLE: roles/resourcemanager.organizationAdmin
Applying role roles/resourcemanager.organizationAdmin to root@landing.systems
Updated IAM policy for organization [59485982875].
bindings:
- members:
  - user:root@landing.systems
  role: roles/accesscontextmanager.policyAdmin
- members:
  - user:michael@landing.systems
  - user:root@landing.systems
  role: roles/billing.creator
- members:
  - user:michael@landing.systems
  - user:root@landing.systems
  role: roles/billing.projectManager
- members:
  - domain:landing.systems
  role: roles/billing.viewer
- members:
  - user:root@landing.systems
  role: roles/compute.networkAdmin
- members:
  - user:root@landing.systems
  role: roles/dns.admin
- members:
  - user:root@landing.systems
  role: roles/logging.admin
- members:
  - user:michael@landing.systems
  - user:root@landing.systems
  role: roles/resourcemanager.folderAdmin
- members:
  - user:michael@landing.systems
  - user:root@landing.systems
  role: roles/resourcemanager.organizationAdmin
- members:
  - user:michael@landing.systems
  - user:root@landing.systems
  role: roles/resourcemanager.projectCreator
- members:
  - user:root@landing.systems
  role: roles/resourcemanager.projectIamAdmin
etag: BwYIKgNC80I=
version: 1
ROLE: roles/resourcemanager.folderAdmin
Applying role roles/resourcemanager.folderAdmin to root@landing.systems
Updated IAM policy for organization [59485982875].
bindings:
- members:
  - user:root@landing.systems
  role: roles/accesscontextmanager.policyAdmin
- members:
  - user:michael@landing.systems
  - user:root@landing.systems
  role: roles/billing.creator
- members:
  - user:michael@landing.systems
  - user:root@landing.systems
  role: roles/billing.projectManager
- members:
  - domain:landing.systems
  role: roles/billing.viewer
- members:
  - user:root@landing.systems
  role: roles/compute.networkAdmin
- members:
  - user:root@landing.systems
  role: roles/dns.admin
- members:
  - user:root@landing.systems
  role: roles/logging.admin
- members:
  - user:michael@landing.systems
  - user:root@landing.systems
  role: roles/resourcemanager.folderAdmin
- members:
  - user:michael@landing.systems
  - user:root@landing.systems
  role: roles/resourcemanager.organizationAdmin
- members:
  - user:michael@landing.systems
  - user:root@landing.systems
  role: roles/resourcemanager.projectCreator
- members:
  - user:root@landing.systems
  role: roles/resourcemanager.projectIamAdmin
etag: BwYIKgNsUD0=
version: 1
ROLE: roles/resourcemanager.projectIamAdmin
Applying role roles/resourcemanager.projectIamAdmin to root@landing.systems
Updated IAM policy for organization [59485982875].
bindings:
- members:
  - user:root@landing.systems
  role: roles/accesscontextmanager.policyAdmin
- members:
  - user:michael@landing.systems
  - user:root@landing.systems
  role: roles/billing.creator
- members:
  - user:michael@landing.systems
  - user:root@landing.systems
  role: roles/billing.projectManager
- members:
  - domain:landing.systems
  role: roles/billing.viewer
- members:
  - user:root@landing.systems
  role: roles/compute.networkAdmin
- members:
  - user:root@landing.systems
  role: roles/dns.admin
- members:
  - user:root@landing.systems
  role: roles/logging.admin
- members:
  - user:michael@landing.systems
  - user:root@landing.systems
  role: roles/resourcemanager.folderAdmin
- members:
  - user:michael@landing.systems
  - user:root@landing.systems
  role: roles/resourcemanager.organizationAdmin
- members:
  - user:michael@landing.systems
  - user:root@landing.systems
  role: roles/resourcemanager.projectCreator
- members:
  - user:root@landing.systems
  role: roles/resourcemanager.projectIamAdmin
etag: BwYIKgOXTvM=
version: 1
ROLE: roles/compute.networkAdmin
Applying role roles/compute.networkAdmin to root@landing.systems
Updated IAM policy for organization [59485982875].
bindings:
- members:
  - user:root@landing.systems
  role: roles/accesscontextmanager.policyAdmin
- members:
  - user:michael@landing.systems
  - user:root@landing.systems
  role: roles/billing.creator
- members:
  - user:michael@landing.systems
  - user:root@landing.systems
  role: roles/billing.projectManager
- members:
  - domain:landing.systems
  role: roles/billing.viewer
- members:
  - user:root@landing.systems
  role: roles/compute.networkAdmin
- members:
  - user:root@landing.systems
  role: roles/dns.admin
- members:
  - user:root@landing.systems
  role: roles/logging.admin
- members:
  - user:michael@landing.systems
  - user:root@landing.systems
  role: roles/resourcemanager.folderAdmin
- members:
  - user:michael@landing.systems
  - user:root@landing.systems
  role: roles/resourcemanager.organizationAdmin
- members:
  - user:michael@landing.systems
  - user:root@landing.systems
  role: roles/resourcemanager.projectCreator
- members:
  - user:root@landing.systems
  role: roles/resourcemanager.projectIamAdmin
etag: BwYIKgPACFY=
version: 1
ROLE: roles/accesscontextmanager.policyAdmin
Applying role roles/accesscontextmanager.policyAdmin to root@landing.systems
Updated IAM policy for organization [59485982875].
bindings:
- members:
  - user:root@landing.systems
  role: roles/accesscontextmanager.policyAdmin
- members:
  - user:michael@landing.systems
  - user:root@landing.systems
  role: roles/billing.creator
- members:
  - user:michael@landing.systems
  - user:root@landing.systems
  role: roles/billing.projectManager
- members:
  - domain:landing.systems
  role: roles/billing.viewer
- members:
  - user:root@landing.systems
  role: roles/compute.networkAdmin
- members:
  - user:root@landing.systems
  role: roles/dns.admin
- members:
  - user:root@landing.systems
  role: roles/logging.admin
- members:
  - user:michael@landing.systems
  - user:root@landing.systems
  role: roles/resourcemanager.folderAdmin
- members:
  - user:michael@landing.systems
  - user:root@landing.systems
  role: roles/resourcemanager.organizationAdmin
- members:
  - user:michael@landing.systems
  - user:root@landing.systems
  role: roles/resourcemanager.projectCreator
- members:
  - user:root@landing.systems
  role: roles/resourcemanager.projectIamAdmin
etag: BwYIKgPmxcU=
version: 1
```

gcloud organizations add-iam-policy-binding $ORG_ID --member=user:$SUPER_ADMIN_EMAIL --role=roles/resourcemanager.organizationAdmin --quiet #> /dev/null 1>&1
gcloud organizations add-iam-policy-binding $ORG_ID --member=user:$SUPER_ADMIN_EMAIL --role=roles/resourcemanager.folderAdmin --quiet #> /dev/null 1>&1
gcloud organizations add-iam-policy-binding $ORG_ID --member=user:$SUPER_ADMIN_EMAIL --role=roles/resourcemanager.projectIamAdmin --quiet #> /dev/null 1>&1
gcloud organizations add-iam-policy-binding $ORG_ID --member=user:$SUPER_ADMIN_EMAIL --role=roles/compute.networkAdmin --quiet #> /dev/null 1>&1
gcloud organizations add-iam-policy-binding $ORG_ID --member=user:$SUPER_ADMIN_EMAIL --role=roles/accesscontextmanager.policyAdmin --quiet #> /dev/null 1>&1
gcloud organizations add-iam-policy-binding $ORG_ID --member=user:$SUPER_ADMIN_EMAIL --role=roles/servicedirectory.editor --quiet #> /dev/null 1>&1
gcloud organizations add-iam-policy-binding $ORG_ID --member=user:$SUPER_ADMIN_EMAIL --role=roles/dns.admin --quiet #> /dev/null 1>&1
gcloud organizations add-iam-policy-binding $ORG_ID --member=user:$SUPER_ADMIN_EMAIL --role=roles/logging.admin --quiet #> /dev/null 1>&1
