### ISSUE TITLE
Automation: One click scripted Landing Zone : onboard org + KCC cluster + core-landing-zone deployment 

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pubsec-declarative-toolkit#595]
As part of automating the core-landing-zone and hub-env see #446 packages deployment a single script was developed that does all 3 steps
- prepare for the landing zone install - onboard the project and super admin account (upgrade to service account impersonation later)
- install the KCC cluster in it's VPC for developer mode (no PSC, NAT, IGW or VPC flow logs required)
- deploy 1 or more packages - currently the core-landing-zone along with generation of its setters.yaml is completed

For example the following setters.yaml is generated from https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/blob/gh446-hub/solutions/setup.sh

```
apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /setters
  name: setters
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|setters'
data: 
  org-id: "59485982875"
  lz-folder-id: "355816628468"
  billing-id: "01E6E8-A42E99-D21FF3"
  management-project-id: "kcc-boot-ls-8704"
  management-project-number: "145363557028"
  management-namespace: config-control
  allowed-trusted-image-projects: |
    - "projects/cos-cloud"
  allowed-contact-domains: |
    - "@landing.systems"
  allowed-policy-domain-members: |
    - "C03lz5ebg"
  allowed-vpc-peering: |
    - "under:organizations/59485982875"
  logging-project-id: logging-project-ls4
  security-log-bucket: security-log-bucket-ls4
  platform-and-component-log-bucket: platform-and-component-log-bucket-ls4
  retention-locking-policy: "false"
  retention-in-days: "1"
  dns-project-id: dns-project-ls4
  dns-name: "landing.systems."
```
