### ISSUE TITLE
hub-env: Ambiguity: determine/rename whether the project-parent-folder requires the name or id - specifies the id but the name is working in the deployment

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pubsec-declarative-toolkit#596]
Still triaging as part of brining up the hub-env in #466 for #258 after the change in #573
The project comes up under the folder ok but I have yet to go through the remaining "kubectl describe" checks on pending kpt render resources that may need the folder numeric id

```
project-parent-folder: project-parent-folder
```
for example if the format is 
```
project-parent-folder: 012345...90
or
project-parent-folder_id: 012345...90
```

the following project deployment was ok with
```
  # GCP folder to use as parent to this project, lowercase K8S resource name - this needs the ID
  project-parent-folder: services-infrastructure
  #project-parent-folder: "176411558066"
```
<img width="659" alt="Screenshot 2023-10-22 at 21 20 39" src="https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/assets/24765473/05220899-599e-4162-b900-1a9198b6485f">

**Comment by obriensystems** [comment]
triaging on on 0.2.1 with/without folder name/id
```
michael@cloudshell:~/kcc-oi/kpt (kcc-oi-3552)$ kpt live apply hub-env
installing inventory ResourceGroup CRD.
error: invalid object: "projects_xxdmu-admin1-hub-oi5_resourcemanager.cnrm.cloud.google.com_Project": invalid "config.kubernetes.io/depends-on" annotation: external dependency: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/xxdmu-admin1-hub-oi5 -> resourcemanager.cnrm.cloud.google.com/namespaces/hierarchy/Folder/services-infrastructure
```

**Comment by obriensystems** [comment]
found it  - I forgot I fixed a hardcoded depends-on dependency in project.yaml off hub-env
```
  annotations:
    cnrm.cloud.google.com/auto-create-network: "false"
    #   config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/hierarchy/Folder/services-infrastructure
    #config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/hierarchy/Folder/176411558066
    internal.kpt.dev/upstream-identifier: 'resourcemanager.cnrm.cloud.google.com|Project|projects|hub-project-id'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg-fn-live'
spec:
  name: dmu-admin1-hub-kls # kpt-set: ${hub-project-id}
```
<img width="2606" alt="Screenshot 2023-10-23 at 13 02 34" src="https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/assets/24765473/4c6ef33b-8258-49e4-b3c0-84c7a89f3cb6">
