### ISSUE TITLE
feat: enable logging on ComputeRouterNAT resources in client-landing-zone

### ISSUE THREAD

**Issue by lucstjean-ssc** [GoogleCloudPlatform/pubsec-declarative-toolkit#637]
Updating client-landing-zone package.

Enables logging for Cloud NAT
https://cloud.google.com/config-connector/docs/reference/resource-docs/compute/computerouternat

**Spec:**
```yaml
logConfig:
  enable: boolean
  filter: string
```

Spec to implement (ALL=Translation and errors):
```yaml
logConfig:
  enable: true
  filter: ALL
```
