### ISSUE TITLE
feat: add storage bucket to core-landing-zone package to hold logs related to events and security incidents

### ISSUE THREAD

**Issue by lucstjean-ssc** [GoogleCloudPlatform/pubsec-declarative-toolkit#640]
Add storage bucket to core-landing-zone package to hold logs related to events and security incidents. These logs are to be manually copied using the procedures outlined in the following guide:
> https://cloud.google.com/logging/docs/routing/copy-logs. 

**Note:** 

Library and Archives Canada (LAC) recommends a retention period of 2 years after last administrative use for information with business value in IT or security processes:
> https://www.canada.ca/en/government/system/digital-government/online-security-privacy/event-logging-guidance.html

Changes in this PR:

- Add IAMPolicyMember (roles/storage.admin)
- Add StorageBucket
  ```yaml
    autoclass:
      enabled: true
    location: northamerica-northeast1
    publicAccessPrevention: "enforced"
    uniformBucketLevelAccess: true
    retentionPolicy:
      isLocked: false
      retentionPeriod: 86400
  ```
- Modify setters
