### ISSUE TITLE
Flip perimeter prod firewall deny rule for ssh:22 to allow - during dev - or flip name to deny to block

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pubsec-declarative-toolkit#75]
Once we get a range or single tunnel proxy or bastion/IAP access going we can flip back to deny

- https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/blob/main/solutions/landing-zone/environments/common/firewall/public-perimeter-firewall.yaml#L53
- https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/environments/common/prod-public-perimeter-firewall.auto.tfvars#L49
```
spec:
  description: Allow SSH Connections from the internet
  direction: INGRESS
  deny:
    - protocol: tcp
      ports: 
      - "22"
  sourceRanges:
    - 0.0.0.0/0
```
