### ISSUE TITLE
The gatekeeper solution deployment by kpt won't start

### ISSUE THREAD

**Issue by jacyang2010** [GoogleCloudPlatform/pubsec-declarative-toolkit#761]
**Describe the bug**
When deploy the gatekeeper solution given below via kpt by following the below guide, the deployment won't start and got some errors about CRDs required are uninstalled.

https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/tree/main/docs/landing-zone-v2

**To Reproduce**

Step1: Install and configure kcc config controller by the above given guide.
Step2: Follow the below command to download and deploy the gatekeeper solution.

Step3: Found the gatekeeper solution deployment won't start.

**Expected behavior**
A reliable solution and guide must be given so that we can install gatekeeper solution without any errors.

**Comment by cartyc** [comment]
This is due to the gatekeeper `ConstraintTemplate` needing to be installed into the Config Controller instance before they can be called by the `constraints` objects. `kpt` does not continually reconcile and leads to this error blocking deployment, if using `config-sync` this will eventually reconcile once the `ConstraintTemplates` get loaded.

In order to work-around this issue you will need to comment out the  `constraint` objects and run a `kpt live apply` and once that has succeeded you can then uncomment the `constraint`'s and re-run `kpt live apply`.  The fix for this is being tracked in #414 . This PR separates the `constraintTemplates` and the `constraints` into their own packages in order to prevent the error that you are experiencing.

**Comment by jacyang2010** [comment]
A better solution could be that, without separating of current yaml files, we can utilize the annotation ```config.kubernetes.io/depends-on``` to specific dependencies of resources so that kpt can know which resources should be applied first. The example code should be like below example.
```
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: DataLocation
metadata: # kpt-merge: /datalocation
  name: datalocation
  annotations:
    internal.kpt.dev/upstream-identifier: 'constraints.gatekeeper.sh|DataLocation|default|datalocation'
    config.kubernetes.io/depends-on: templates.gatekeeper.sh/ConstraintTemplate/datalocation # Look at here
...
```
Please refer to the below document from kpt for more details.
https://kpt.dev/book/06-deploying-packages/03-handling-dependencies
