### ISSUE TITLE
Ambiguity: client-project-setup setters.yaml folder ID, name or metaname - clarify in setters docs

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pubsec-declarative-toolkit#829]
```
  # GCP folder to use as parent to this project
  # the values must match the kubernetes resources 'metadata.name', for example "standard.applications.nonp"
  # customization: required
  project-parent-folder: project-parent-folder
```
Setting as Id for now
as in 
<img width="1275" alt="Screenshot 2024-02-13 at 16 56 05" src="https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/assets/24765473/1cc2adb6-9733-449d-b714-9891b440298b">

name on standard.applications.nonp
```
michael@cloudshell:~/kcc-cso/github (kcc-cso-4380)$ gcloud resource-manager folders describe 202541361947
createTime: '2024-02-06T17:58:03.940Z'
displayName: nonp
lifecycleState: ACTIVE
name: folders/202541361947
parent: folders/1095956291549
```

**Comment by obriensystems** [comment]
client-project-setup
```
data:
  org-id: "${ORG_ID}"  
  management-project-id: "${KCC_PROJECT_ID}"
  management-namespace: "${MANAGEMENT_NAMESPACE}"
  client-name: client-${PREFIX_CLIENT_SETUP}
  client-management-project-id: client-management-project-${PREFIX_CLIENT_SETUP}
  host-project-id: net-host-project-${PREFIX_CLIENT_LANDING_ZONE}
  # see https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/blob/main/solutions/client-landing-zone/client-folder/standard/applications-infrastructure/host-project/network/subnet.yaml#L26
  #allowed-nane1-main-subnet: net-host-project-${PREFIX_CLIENT_LANDING_ZONE}-nane1-standard-${CLIENT_CLASSIFICATION}-main-snet
  #allowed-nane2-main-subnet: net-host-project-${PREFIX_CLIENT_LANDING_ZONE}-nane2-standard-${CLIENT_CLASSIFICATION}-main-snet
  allowed-nane1-main-subnet: nane1-standard-${CLIENT_CLASSIFICATION}-main-snet
  allowed-nane2-main-subnet: nane2-standard-${CLIENT_CLASSIFICATION}-main-snet
  project-id: client-project-${PREFIX_CLIENT_PROJECT_SETUP}
  project-billing-id: "${BILLING_ID}"
#  project-parent-folder: clients.client-${PREFIX_CLIENT_SETUP}.standard.applications-infrastructure.${CLIENT_PROJECT_PARENT_FOLDER}
  project-parent-folder: standard.applications.${CLIENT_PROJECT_PARENT_FOLDER}
  repo-url: git-repo-to-observe
  repo-branch: main
  tier3-repo-dir: csync/tier3/configcontroller/deploy/env
  tier4-repo-dir: csync/tier4/configcontroller/deploy/env
```
